# Background and foreground colors
background = #030614
foreground = #ffffff

# Standard colors
palette = 0=#030614
palette = 1=#b67281
palette = 2=#3aebfd
palette = 3=#5fe8fa
palette = 4=#9096c6
palette = 5=#baa6bf
palette = 6=#2adef4
palette = 7=#def9fd

# Bright colors
palette = 8=#5060ad
palette = 9=#d7adb6
palette = 10=#94f5ff
palette = 11=#b6f6ff
palette = 12=#cbcee6
palette = 13=#e4dbe6
palette = 14=#7bf0fe
palette = 15=#ffffff
