background            #030614
foreground            #ffffff

# black
color0  #030614
color8  #5060ad

# red
color1  #b67281
color9  #d7adb6

# green
color2  #3aebfd
color10 #94f5ff

# yellow
color3  #5fe8fa
color11 #b6f6ff

# blue
color4  #9096c6
color12 #cbcee6

# magenta
color5  #baa6bf
color13 #e4dbe6

#cyan
color6  #2adef4
color14 #7bf0fe

#white
color7  #def9fd
color15 #ffffff


